;
; Dragon BASIC tokens.
; 

DgnFOR		equ	$80	
DgnGO		equ	$81	
DgnREM		equ	$82	
DgnREM2		equ	$83	
DgnELSE		equ	$84	
DgnIF		equ	$85	
DgnDATA		equ	$86	
DgnPRINT	equ	$87	
DgnON		equ	$88	
DgnINPUT	equ	$89	
DgnEND		equ	$8a	
DgnNEXT		equ	$8b	
DgnDIM		equ	$8c	
DgnREAD		equ	$8d	
DgnLET		equ	$8e	
DgnRUN		equ	$8f	
DgnRESTORE	equ	$90	
DgnRETURN	equ	$91	
DgnSTOP		equ	$92	
DgnPOKE		equ	$93	
DgnCONT		equ	$94	
DgnLIST		equ	$95	
DgnCLEAR	equ	$96	
DgnNEW		equ	$97	
DgnDEF		equ	$98	
DgnCLOAD	equ	$99	
DgnCSAVE	equ	$9a	
DgnOPEN		equ	$9b	
DgnCLOSE	equ	$9c	
DgnLLIST	equ	$9d	
DgnSET		equ	$9e	
DgnRESET	equ	$9f	
DgnCLS		equ	$a0	
DgnMOTOR	equ	$a1	
DgnSOUND	equ	$a2	
DgnAUDIO	equ	$a3	
DgnEXEC		equ	$a4	
DgnSKIPF	equ	$a5	
DgnDEL		equ	$a6	
DgnEDIT		equ	$a7	
DgnTRON		equ	$a8	
DgnTROFF	equ	$a9	
DgnLINE		equ	$aa	
DgnPCLS		equ	$ab	
DgnPSET		equ	$ac	
DgnPRESET	equ	$ad	
DgnSCREEN	equ	$ae	
DgnPCLEAR	equ	$af	
DgnCOLOR	equ	$b0	
DgnCIRCLE	equ	$b1	
DgnPAINT	equ	$b2	
DgnGET		equ	$b3	
DgnPUT		equ	$b4	
DgnDRAW		equ	$b5	
DgnPCOPY	equ	$b6	
DgnPMODE	equ	$b7	
DgnPLAY		equ	$b8	
DgnDLOAD	equ	$b9	
DgnRENUM	equ	$ba	
DgnTAB		equ	$bb	
DgnTO		equ	$bc	
DgnSUB		equ	$bd	
DgnFN		equ	$be	
DgnTHEN		equ	$bf	
DgnNOT		equ	$c0	
DgnSTEP		equ	$c1	
DgnOFF		equ	$c2	
DgnPlus		equ	$c3	
DgnMinus	equ	$c4	
DgnTimes	equ	$c5	
DgnDivide	equ	$c6	
DgnPower	equ	$c7	
DgnAND		equ	$c8	
DgnOR		equ	$c9	
DgnGt		equ	$ca	
DgnEq		equ	$cb	
DgnLt		equ	$cc	
DgnUSING	equ	$cd	

; DragonDOS command tokens
DgnAUTO		equ	$ce	
DgnBACKUP	equ	$cf	
DgnBEEP		equ	$d0	
DgnBOOT		equ	$d1	
DgnCHAIN	equ	$d2	
DgnCOPY		equ	$d3	
DgnCREATE	equ	$d4	
DgnDIR		equ	$d5	
DgnDRIVE	equ	$d6	
DgnDSKINIT	equ	$d7	
DgnFREAD	equ	$d8	
DgnFWRITE	equ	$d9	
DgnERROR	equ	$da	
DgnKILL		equ	$db	
DgnLOAD		equ	$dc	
DgnMERGE	equ	$dd	
DgnPROTECT	equ	$de	
DgnWAIT		equ	$df	
DgnRENAME	equ	$e0	
DgnSAVE		equ	$e1	
DgnSREAD	equ	$e2	
DgnSWRITE	equ	$e3	
DgnVERIFY	equ	$e4	
DgnFROM		equ	$e5	
DgnFLREAD	equ	$e6	
DgnSWAP		equ	$e7	

; Dragon DragonMMC Command tokens

DgnMCAS		equ	$e8
DgnMMIRROR	equ	$e9
DgnMMOUNT	equ	$ea
DgnHELP		equ	$eb
DgnRAMBOOT	equ	$ec
DgnCAT		equ	$ed
DgnMDELETE	equ	$ee
DgnMSAVE	equ	$ef
DgnMLOAD	equ	$f0
DgnMCARTLOAD	equ	$f1
DgnMTAPERUN	equ	$f2
DgnCWD		equ	$f3
DgnMSETCFG	equ	$f4
DgnRETOK	equ	$f5
DgnMDISK	equ	$f6
DgnREWIND	equ	$f7
DgnMSETDT	equ	$f8
DgnMKDIR	equ	$f9
		
;Dragon BASIC Function tokens - all proceeded by equ	$ff to differentiate from operators
DgnSGN		equ	$80	
DgnINT		equ	$81	
DgnABS		equ	$82	
DgnPOS		equ	$83	
DgnRND		equ	$84	
DgnSQR		equ	$85	
DgnLOG		equ	$86	
DgnEXP		equ	$87	
DgnSIN		equ	$88	
DgnCOS		equ	$89	
DgnTAN		equ	$8a	
DgnATN		equ	$8b	
DgnPEEK		equ	$8c	
DgnLEN		equ	$8d	
DgnSTRS		equ	$8e	
DgnVAL		equ	$8f	
DgnASC		equ	$90	
DgnCHRS		equ	$91	
DgnEOF		equ	$92	
DgnJOYSTK	equ	$93	
DgnFIX		equ	$94	
DgnHEXS		equ	$95	
DgnLEFTS	equ	$96	
DgnRIGHTS	equ	$97	
DgnMIDS		equ	$98	
DgnPOINT	equ	$99	
DgnINKEYS	equ	$9a	
DgnMEM		equ	$9b	
DgnVARPTR	equ	$9c	
DgnINSTR	equ	$9d	
DgnTIMER	equ	$9e	
DgnPPOINT	equ	$9f	
DgnSTRINGS	equ	$a0	
DgnUSR		equ	$a1	

; DragonDOS function tokens
DgnLOF		equ	$a2	
DgnFREE		equ	$a3	
DgnERL		equ	$a4	
DgnERR		equ	$a5	
DgnHIMEM	equ	$a6	
DgnLOC		equ	$a7	
DgnFRES		equ	$a8	

;Dragon DragonMMC function tokens

DgnVER		equ	$a9
DgnWDS		equ	$aa
DgnFINDFIRSTS	equ	$ab
DgnFINDNEXTS	equ	$ac
DgnCFTYPE	equ	$ad
DgnMGETCFG	equ	$ae
DgnMGETDTS	equ	$af
DgnMGETINAMES	equ	$b0
DgnSDS		equ	$b1

; CoCo BASIC command tokens

CoFOR		equ	$80
CoGO		equ	$81
CoREM		equ	$82
CoREM2		equ	$83
CoELSE		equ	$84
CoIF		equ	$85
CoDATA		equ	$86
CoPRINT		equ	$87
CoON		equ	$88
CoINPUT		equ	$89
CoEND		equ	$8a
CoNEXT		equ	$8b
CoDIM		equ	$8c
CoREAD		equ	$8d
CoRUN		equ	$8e
CoRESTORE	equ	$8f
CoRETURN	equ	$90
CoSTOP		equ	$91
CoPOKE		equ	$92
CoCONT		equ	$93
CoLIST		equ	$94
CoCLEAR		equ	$95
CoNEW		equ	$96
CoCLOAD		equ	$97
CoCSAVE		equ	$98
CoOPEN		equ	$99
CoCLOSE		equ	$9a
CoLLIST		equ	$9b
CoSET		equ	$9c
CoRESET		equ	$9d
CoCLS		equ	$9e
CoMOTOR		equ	$9f
CoSOUND		equ	$a0
CoAUDIO		equ	$a1
CoEXEC		equ	$a2
CoSKIPF		equ	$a3
CoTAB		equ	$a4
CoTO		equ	$a5
CoSUB		equ	$a6
CoTHEN		equ	$a7
CoNOT		equ	$a8
CoSTEP		equ	$a9
CoOFF		equ	$aa
CoPlus		equ	$ab
CoMinus		equ	$ac
CoTimes		equ	$ad
CoDivide 	equ	$ae
CoPower		equ	$af
CoAND		equ	$b0
CoOR		equ	$b1
CoGt		equ	$b2
CoEq		equ	$b3
CoLt		equ	$b4
CoDEL		equ	$b5
CoEDIT		equ	$b6
CoTRON		equ	$b7
CoTROFF		equ	$b8
CoDEF		equ	$b9
CoLET		equ	$ba
CoLINE		equ	$bb
CoPCLS		equ	$bc
CoPSET		equ	$bd
CoPRESET	equ	$be
CoSCREEN	equ	$bf
CoPCLEAR	equ	$c0
CoCOLOR		equ	$c1
CoCIRCLE	equ	$c2
CoPAINT		equ	$c3
CoGET		equ	$c4
CoPUT		equ	$c5
CoDRAW		equ	$c6
CoPCOPY		equ	$c7
CoPMODE		equ	$c8
CoPLAY		equ	$c9
CoDLOAD		equ	$ca
CoRENUM		equ	$cb
CoFN		equ	$cc
CoUSING		equ	$cd

; RSDOS adds these .. (from Dragon User 12/84)
CoDIR		equ	$ce
CoDRIVE		equ	$cf
CoFIELD		equ	$d0
CoFILES		equ	$d1
CoKILL		equ	$d2
CoLOAD		equ	$d3
CoLSET		equ	$d4
CoMERGE		equ	$d5
CoRENAME	equ	$d6
CoRSET		equ	$d7
CoSAVE		equ	$d8
CoWRITE		equ	$d9
CoVERIFY	equ	$da
CoUNLOAD	equ	$db
CoDSKINI	equ	$dc
CoBACKUP	equ	$dd
CoCOPY		equ	$de
CoDSKIS		equ	$df
CoDSKOS		equ	$e0
CoDOS       equ $e1

; Dragon DragonMMC Command tokens

CoMCAS		equ	$e2
CoMMIRROR	equ	$e3
CoMMOUNT	equ	$e4
CoHELP		equ	$e5
CoRAMBOOT	equ	$e6
CoCAT		equ	$e7
CoMDELETE	equ	$e8
CoMSAVE		equ	$e9
CoMLOAD		equ	$ea
CoMCARTLOAD	equ	$eb
CoMTAPERUN	equ	$ec
CoCWD		equ	$ed
CoMSETCFG	equ	$ee
CoRETOK		equ	$ef
CoMDISK		equ	$f0
CoREWIND	equ	$f1
CoMSETDT	equ	$f2
CoMKDIR		equ	$f3


;Function tokens - all proceeded by $ff to differentiate from operators
;Token  Keyword
CoSGN		equ	$80
CoINT		equ	$81
CoABS		equ	$82
CoUSR		equ	$83
CoRND		equ	$84
CoSIN		equ	$85
CoPEEK		equ	$86
CoLEN		equ	$87
CoSTRS		equ	$88
CoVAL		equ	$89
CoASC		equ	$8a
CoCHRS		equ	$8b
CoEOF		equ	$8c
CoJOYSTK	equ	$8d
CoLEFTS		equ	$8e
CoRIGHTS	equ	$8f
CoMIDS		equ	$90
CoPOINT		equ	$91
CoINKEYS	equ	$92
CoMEM		equ	$93
CoATN		equ	$94
CoCOS		equ	$95
CoTAN		equ	$96
CoEXP		equ	$97
CoFIX		equ	$98
CoLOG		equ	$99
CoPOS		equ	$9a
CoSQR		equ	$9b
CoHEXS		equ	$9c
CoVARPTR	equ	$9d
CoINSTR		equ	$9e
CoTIMER		equ	$9f
CoPPOINT	equ	$a0
CoSTRINGS	equ	$a1

; RSDOS adds these .. (from Dragon User 12/84)
CoCVN		equ	$a2
CoFREE		equ	$a3
CoLOC		equ	$a4
CoLOF		equ	$a5
CoMKNS		equ	$a6
CoAS		equ	$a7

; CoCo DragonMMC function tokens

CoVER		equ	$a8
CoWDS		equ	$a9
CoFINDFIRSTS	equ	$aa
CoFINDNEXTS	equ	$ab
CoCFTYPE	equ	$ac
CoMGETCFG	equ	$ad
CoMGETDTS	equ	$ae
CoMGETINAMES	equ	$af
CoSDS		equ	$b0
