DosCmdNames   
        fcs     /DIR/                   ; $CE           
        fcs     /DRIVE/                 ; $CF
        fcs     /FIELD/                 ; $D0
        fcs     /FILES/                 ; $D1 
        fcs     /KILL/                  ; $D2
        fcs     /LOAD/                  ; $D3
        fcs     /LSET/                  ; $D4
        fcs     /MERGE/                 ; $D5
        fcs     /RENAME/                ; $D6
        fcs     /RSET/                  ; $D7
        fcs     /SAVE/                  ; $D8
        fcs     /WRITE/                 ; $D9
        fcs     /VERIFY/                ; $DA
        fcs     /UNLOAD/                ; $DB
        fcs     /DSKINI/                ; $DC
        fcs     /BACKUP/                ; $DD
        fcs     /COPY/                  ; $DE
        fcs     /DSKI$/                 ; $DE
        fcs     /DSKO$/                 ; $E0
        fcs     /DOS/                   ; $E1
